.PHONY:all
all:OneToN1 OneToN2 OneToN3 OneToN4

OneToN1:OneToN_1.cpp
	g++ -o OneToN1 OneToN_1.cpp
OneToN2:OneToN_2.cpp
	g++ -o OneToN2 OneToN_2.cpp
OneToN3:OneToN_3.cpp
	g++ -o OneToN3 OneToN_3.cpp
OneToN4:OneToN_4.cpp
	g++ -o OneToN4 OneToN_4.cpp

.PHONY:clean
clean:
	rm -f OneToN1 OneToN2 OneToN3 OneToN4
